---
title: "Intro to Data Structures"
type: "article"
description: "Discusses how the data structure being used affects the performance of different operations."
tags: "data-structure, computer-science, linked-list, dynamic-array"
