---
title: "Big O Notation"
type: "article"
description: "Describes how to classify an algorithm's performance as it handles more data."
tags: "big-o-notation, optimization, algorithm, computer-science, binary-search"
