---
title: "Rails Nested Resources"
type: "article"
description: "Describes how to organize URLs for parent-child relationships between resources."
tags: "rails, resources, controllers, routes, one-to-many, nested-resources"
