---
title: "Intro to Object-Oriented Programming"
type: "article"
description: "Describes how we can define custom objects to combine data and the methods that operate on it."
tags: "objects, classes, instance-variables, methods"
