def twitter_data
  [{"LaunchAcademy_"=>
   {"description"=>
     "A 10 week, intensive bootcamp teaching you how to code with a focus on Ruby on Rails",
    "last twenty tweets"=>
     ["RT @chrisccerami: While learning web development I created a map of all of the shows @Screamales have played and damn @DonGiovanniRecs http…",
      "6 ways to quantify your code and why you need to do it: http://t.co/1WKtpo41tP by @kevinrcasey http://t.co/lulzPLTY8c",
      "Do more of what you want at work. How to create productive partnerships: http://t.co/QpYpHhHEid by @benvoss",
      "RT @Pistachio: SO rad. bunch of local women learning to code with @gdiBoston at @HubSpot right now: http://t.co/jaIxK7suOj",
      "RT @STWatkins78: Huge breakthrough on my breakable toy today...can upload local file to soundcloud from my app...time for a beer! #LaunchAc…",
      "Just say yes to opportunities, especially if they scare you. http://t.co/LcF2ilwKDu great advice by @kerry_benjamin1",
      "How the internet is changing software and business, using Ruby as an example: http://t.co/EMYeLa0se7 by  @ukitazume http://t.co/wNymPXcvAr",
      "RT @chrisccerami: @JustusEapen @LaunchAcademy_ @MarsCuriosity https://t.co/W6IBpIuIr0",
      "Come build some interesting projects! @womenwhocode Hack Night tomorrow. RSVP: http://t.co/wPgaQfQjVp http://t.co/sI5lIn9bJ9",
      "RT @SpencerCDixon: One of the greatest parts of being a developer is the massive amount of control you have over a computer. Feels very emp…",
      "7 reasons to love Minitest for testing Ruby code: http://t.co/Qbq5Wtb3RC by @FluxusFrequency, a graduate from our friends @gschool",
      "Interested in becoming a game developer? Here's how: http://t.co/xDJDzzFxA8 via @skilledup http://t.co/ir4GphhU3m",
      "Web developer hiring trends, and what they mean for you: http://t.co/0Ajg7TdQFm by @walesmd http://t.co/coRokF42kA",
      "RT @chrisccerami: I recently built my first API in Rails which I hope makes photos from Mars courtesy of @MarsCuriosity more accessible to …",
      "Build things that last. Make sure your work lives beyond you. http://t.co/YMbuOwhY36 by @acolangelo",
      "Thanks to everyone who came to Ship It! Saturday! Check out the latest blog post for a recap: http://t.co/EYSeUc87qQ http://t.co/pAG5x0GzTa",
      "Write your code as if your best friend's inheriting it http://t.co/kbtLURrPcN by @MGraybosch http://t.co/JesBAjwIiB",
      "Coding can improve the way we run the world. Old, but inspiring TED talk by @pahlkadot: http://t.co/mu7QqTZK6L http://t.co/Qol943YcX3",
      "Practicing pitches and getting ready for Career Day, coming up on January 27th and 28th! http://t.co/fxCcFIIMTc",
      "RT @lizvdk: The cool kids use GEOjson so I did too. Here's how I build it with Ruby: https://t.co/sXFTW9nzWb"],
    "number of followers"=>3590,
    "number of friends"=>699,
    "latest tweet"=>
     "RT @chrisccerami: While learning web development I created a map of all of the shows @Screamales have played and damn @DonGiovanniRecs http…",
    "number of tweets"=>1433,
    "location"=>"Boston, MA"}},
 {"dpickett"=>
   {"description"=>"Co-Founder at @LaunchAcademy_, Co-Organizer of @bostonrb",
    "last twenty tweets"=>
     ["RT @MeetingBoy: If your employees worked until 3AM, you have failed as a manager.",
      "Glad to see two organizations that are near and dear to me (@EntrepreneurOrg and @YEC) at the top of this list: http://t.co/7PfhJeRWZi",
      "@lizvdk I had the same reaction - it was like they spent the last 45 minutes  trolling the movie industry.",
      "RIP @jamesgolick - I learned so much from you, and always thought you were one of the most professional and skilled devs I've ever met :-(",
      "Aspiring devs, if you need an example of a professional that embodies all we try to teach and more, look to @hchood Thank you! I'll miss you",
      "Some notes for my facilitation tomorrow on debugging JavaScript: http://t.co/AdDGpCCfM2",
      "@marcomorawec and @kenmazaika great having you guys at Mission Control! Love meeting folks with their hearts in technical education :-)",
      "RT @graysky: \"Resumes suck. Here’s the data.\" by @alinelernerLLC http://t.co/jnN7FXzsPh Most create similar, unhelpful resume",
      "@paulanthonywils @searls @markbates I reported the @bostonrb imitator as spam. Seems like the right thing to do",
      "@divineanimal @launchacademy_ we're delighted to have you! :-) See you soon and keep us posted on how prelearning is going.",
      "sad to hear about @ezmobius passing. His work at @engineyard and some of his conference talks blew my mind. A source of wisdom for many. RIP",
      "Thank you! http://t.co/IIaQqRKzc9",
      "@jboursiquot happy birthday man!",
      "lol! the irony of this error message! http://t.co/CkJD0zBrMF",
      "such refreshing honesty \"If you really believe that you and your business are one, business failure destroys you\" @ http://t.co/jouSrHzOFJ",
      "RT @bostonrb: Instead of our monthly meeting, we're going to party in December! Join us at the Black Rose on 12/9 @ 7PM. RSVP @ https://t.c…",
      "@dan_kleiman @launchacademy_ @heroiceric Mr. G is shedding a tear right now.",
      "@kdaigle I always consider there to be a 2 or 3 year lag in enterprise adoption of ideas like that.",
      "Change is good. \"Why Google doesn’t care about hiring top college graduates\" http://t.co/TA9wXlKoOZ by @MaxNisen",
      "This is why I can't read TechCrunch. What an uninformed piece, and a total misunderstanding of the term \"full stack\" http://t.co/vdv9rOSI6K"],
    "number of followers"=>1604,
    "number of friends"=>874,
    "latest tweet"=>
     "RT @MeetingBoy: If your employees worked until 3AM, you have failed as a manager.",
    "number of tweets"=>3451,
    "location"=>"ÜT: 42.132759,-71.132183"}},
 {"STWatkins78"=>
   {"description"=>nil,
    "last twenty tweets"=>
     ["Huge breakthrough on my breakable toy today...can upload local file to soundcloud from my app...time for a beer! #LaunchAcademy",
      "@SCsupport I got it to work! Thank again for your support though.",
      "@SoundCloud see previous tweet http://t.co/lLBiNv8qtM",
      "@SoundCloud When trying to implement your API on RoR app, I receive a 502BadGateway error when trying to upload an audio file...what gives?",
      "RT @resilientcoders: Team Resilient at the @LaunchAcademy_ Ship it Saturday. Big thx to @STWatkins78 for lending his expertise in rails! ht…",
      "@nfl re-evaluate the Rooney rule. Teams interview men of color to satisfy a requirement when they already know who they will hire. #farce",
      "Check out \"Ship It! Saturday Hackathon at Launch Academy\" http://t.co/qK5MIv7AHN via @eventbrite",
      "Coming soon to a #github repo near you. #DoYouEvenLiftBro? http://t.co/OPJC3gKBH1",
      "Mom starts the game off with 70 point \"stanged\". Yes, it's a word. @yoadrienne14 http://t.co/DOjXaISE7K",
      "@RajonRondo , thank you for your contributions to the Celtics. Your selfless play and relentless tenacity will be truly missed. God bless.",
      "Javascript tomorrow. Let the crazy syntax, vars, prompts, and alerts begin! #LaunchAcademy",
      "Building #meowspace today...right meow #LaunchAcademy",
      "Brady to Gronk...too easy",
      "Nothing more ironic than Jehovah's Witnesses soliciting in a predominantly Jewish neighborhood.",
      "@phish I get weird stares when people hear Phish in my car, I cant wait to see their faces when they hear \"Your Pet Cat\". #phish #couchtour",
      "Wanna wait in a line? Try out the douchiest bar in Boston @TavernSqAllston http://t.co/8vPDoivK2J",
      "@marty_walsh Street paving on Buchanan Road at 1 AM? Unacceptable Mr. Mayor. Tell NSTAR to cut the sh*t.",
      "@united thanks for hooking it up with the generous legroom http://t.co/g6cLGAXAr9",
      "@nflredzone #quadboxsighting http://t.co/rCjU6lDLEO",
      "@CharlesGehret best of luck to you bro, i'd vote for ya if i lived in PA"],
    "number of followers"=>24,
    "number of friends"=>84,
    "latest tweet"=>
     "Huge breakthrough on my breakable toy today...can upload local file to soundcloud from my app...time for a beer! #LaunchAcademy",
    "number of tweets"=>21,
    "location"=>nil}},
 {"chrisccerami"=>
   {"description"=>
     "Environmental Scientist | BS in Biology | Soon to be @launchacademy_ student | Aspiring Web Developer",
    "last twenty tweets"=>
     ["@dongiovannirecs @screamales here's where it's hosted right now if you want to check out the interactive map https://t.co/NkgVIXNPxf",
      "@dongiovannirecs @screamales it was way easier because they're done such a good job of cataloging their shows on the site. Made my job easy",
      "@screamales @dongiovannirecs also each tag represents a single venue, and not even all of the shows they've played their",
      "@screamales @dongiovannirecs actually to be fair I had to exclude a dozen or so shows because I didn't have their address. Still leaves ~900",
      "While learning web development I created a map of all of the shows @Screamales have played and damn @DonGiovanniRecs http://t.co/ZAUf5KGmlM",
      "RT @saladinahmed: Yes, that's probably it. http://t.co/ixrJWT8cHo",
      "RT @ethiopiennesays: In light of #Selma snubs in #OscarNoms, it's worth (re)remembering who the Oscars voters are: http://t.co/dEnFQ97ozV h…",
      "RT @BitchMedia: #FridayReads: Check out this book that shares stories of queer and trans artists of color. http://t.co/5HNFsjaLMH http://t.…",
      "RT @femfreq: \"Leelah Alcorn's death inspired two developers to launch a trans-centered game jam” Please support #JamForLeelah! http://t.co/…",
      "RT @BitchMedia: The Corin-Carrie-Janet trifecta on the new @Sleater_Kinney album creates a powerful energy. http://t.co/vwP1IMTo6C http://t…",
      "@auroreounjian debt is the true american dream.",
      "@MeanCreek @AuroreOunjian Young and Wild totally makes me feel exactly that. You guys are on fucking point.",
      "RT @bfod: “…and instead highlight the importance of sustained effort for top-level success in their field.” http://t.co/enP5901Fgf",
      "RT @bfod: Wow, look at those charts: “Academics who wish to diversify their fields might want to downplay talk of innate intellectual gifte…",
      "@lizvdk go for it. it's good to know the strengths of each of those services.",
      "@lizvdk I used Mapbox mostly because I wanted to customize my visualizations based on my data. What made you want to switch back?",
      "@JustusEapen @LaunchAcademy_ @MarsCuriosity https://t.co/W6IBpIuIr0",
      "RT @TheQuinnspiracy: You dont lose ANY rights for doing sex work. Insisting otherwise makes you trash.",
      "RT @TheQuinnspiracy: You don't lose the right to privacy for having done sex work.",
      "RT @TheQuinnspiracy: Someone doing sex work under a different name and not going public doesnt justify you trying to weaponize that work to…"],
    "number of followers"=>37,
    "number of friends"=>81,
    "latest tweet"=>
     "@dongiovannirecs @screamales here's where it's hosted right now if you want to check out the interactive map https://t.co/NkgVIXNPxf",
    "number of tweets"=>1815,
    "location"=>"New Jersey, USA"}},
 {"spencercdixon"=>
   {"description"=>
     "Software Developer & Mentor @launchacademy_ | Cutco FSM | Ruby Enthusiast | Outdoor Adventurer",
    "last twenty tweets"=>
     ["So pumped for snowboarding tomorrow!",
      "@davidgeary just bought the book, excited to jump into some canvas and make some cool games :D",
      "Brought the dog to work today. Best day ever :)",
      "One of the greatest parts of being a developer is the massive amount of control you have over a computer. Feels very empowering",
      "What should we name the astronaut in our launch academy logo?",
      "Discipline is the mother of skill. Make your mornings count. #MiracleMorning",
      "Night snowboarding at wachusett, great end to the weekend!",
      "RT @resilientcoders: Team Resilient at the @LaunchAcademy_ Ship it Saturday. Big thx to @STWatkins78 for lending his expertise in rails! ht…",
      "@searls reminds me of that saying.. If the talk is 5 min il be ready in a week, 20 min in a few days, a hour and I'm ready to go now",
      "@CorinneBabbles one my best friends just made 30 under 30! He's big supporter of launch :)",
      "@HeroicEric Rust 1.0 alpha just released, whens the meetup happening??!",
      "Decided to not shave until I break my GitHub streak. My level of beard will now be in direct proportion to coding skills :)",
      "Great thing about big headphones is they act as earmuffs in the winter :)",
      "You should focus relentlessly on something you're good at, before that you must think hard about whether it will be valuable in the future",
      "When you're on purpose it's a lot harder to make excuses",
      "Integrating Flowdock API into a rails app: http://t.co/mM9VrOb0Lu",
      "Counter Caching in Rails: http://t.co/7qlqnee7Bl",
      "@abderhasan vim :)",
      "@BigCam010 lol touché",
      "Short term gratification is the killer of dreams. Let's make 2015 the year of long-term gratification ;)"],
    "number of followers"=>952,
    "number of friends"=>141,
    "latest tweet"=>"So pumped for snowboarding tomorrow!",
    "number of tweets"=>149,
    "location"=>"Boston, MA"}},
 {"corinnebabbles"=>
   {"description"=>
     "Director of Talent at Launch Academy. Interested in tech, travel, and finding the best nachos in Boston. Oxford comma enthusiast.",
    "last twenty tweets"=>
     ["How many new supporters do you think this led to? - Protests on I-93 Cause Major Traffic Delays; 17 Arrested http://t.co/L1XqhUZRdm",
      "Two Filmmakers Make the Coolest Timelapse of Boston Yet http://t.co/N6Xuxt7PK2",
      "@ReclusiveCakes although, I could be swayed by a realistic plan for reliable public transportation...",
      "RT @ReclusiveCakes: Can I donate to a fund that will help get any location other than Boston for the Olympics? #NoBoston2024",
      "Boston shines on Forbes’ 30 Under 30 lists http://t.co/djw6OYyuc9 via @BetaBoston",
      "Happy International Programmer's Day to our Launchers (past, present, and future), hiring partners, and members of tech community!",
      "RT @nytimes: Breaking News: At Least 11 Killed in Shooting Attack on Paris Newspaper\nhttp://t.co/x03Wx1u2aw",
      "Travel Habits of Americans: 42 Percent Didn't Take Any Vacation Days in 2014 http://t.co/ZfKT44D2mG by @skift",
      "RT @TUGGorg: Were you a volunteer for #TechGivesBack last year? Check out this sweet video! https://t.co/9Uu4hLO4uU",
      "RT @Groupize: Mobile, millennials and technology will be among the trends that take center stage during 2015, http://t.co/IaeCSARX5a",
      "Does anyone actually hire from programming bootcamps? Live discussion on HN - https://t.co/Uiz0VIL5Ya. Thanks for the tip @techiferous!",
      "New Year, New Talent @LaunchAcademy_. Come meet our phenomenal Winter cohort at Career Day 1/27 or 1/28 - http://t.co/2EeHzUOlD7.",
      "Ayn Rand Reviews Children’s Movies http://t.co/O98YaYFehf via @newyorker",
      "10 More Boston Tech Companies to Watch in 2015 http://t.co/etRuDJyN2m",
      "RT @BostonGlobe: The Patriots have reached the postseason 11 of the last 12 years, but they appreciate it every time http://t.co/bnUC9RSuUY",
      "@kingbrianjames - Mortally Wounded Pirate Bay Enters 2015 in Uncertainty | TorrentFreak http://t.co/XkmZiFPDy1",
      "8 Up-and-Coming Startups Who Launched in 2014 http://t.co/UrITHkpMyj",
      "RT @LaunchAcademy_: Kick off 2015 in style by building awesome projects! Join us @ Ship It! Saturday on 1/10. RSVP now: http://t.co/Gp9ncWr…",
      "Google got it wrong. The open-office trend is destroying the workplace. http://t.co/JrcaAWAEHP",
      "Or shrinking seats?"],
    "number of followers"=>369,
    "number of friends"=>439,
    "latest tweet"=>
     "How many new supporters do you think this led to? - Protests on I-93 Cause Major Traffic Delays; 17 Arrested http://t.co/L1XqhUZRdm",
    "number of tweets"=>299,
    "location"=>"Boston, MA"}},
 {"dot_the_speck"=>
   {"description"=>nil,
    "last twenty tweets"=>
     ["@lizvdk You are awesome! It will all be good!",
      "I just used an 'unless/else' in Ruby. YES I DID. THE REBELLION STARTS HERE. #ruby #rebelwithanunlesselse #breakingthecodingconvention",
      "@ScottMadin @WelcomeToDot Keep up this myth. Rent stays low.",
      "RT @_FloridaMan: I am never leaving Florida \n\n#FiveWordsToRuinADate",
      "Either I am a crazy person babbling to myself or I am a Launcher planning her Career Day pitch. You decide. @LaunchAcademy_",
      "Some guy in full cowboy gear walking down Geneva Ave. yelling 'Patriots won!' #dorchester",
      "@NickCluc Or possibly one additional job, like playing QB when you are a WR",
      "Spent my AM helping a student mentor from @resilientcoders learn a bit about Rails. Pretty sure he'll have the whole app done by the PM.",
      "What's stopping you from smoking a joint while waiting for the T? Nothing, says one intrepid Fields Corner commuter. #Dorchester",
      "@WelcomeToDot Nothing like that long, long view of Dorchester as you reflect on how you could have possibly taken the wrong freaking train.",
      "@maureencaught #ThingsGentrifiersDo: have car stickers showing pride in their neighborhood. #ThingsLocalsDo: try to leave the neighborhood",
      "@WelcomeToDot Dorchester tumbleweed/Christmas trees are afoot http://t.co/QhJ5O6N1sP",
      "@judngu Thanks, I let a friend know and he took advantage of it!",
      "@WelcomeToDot @BetaBoston @gallonofallan @hackthehood @BlackGirlsCode (I'm one of the volunteers for that cohort)",
      "@WelcomeToDot @BetaBoston @gallonofallan @hackthehood @BlackGirlsCode Try @resilientcoders, there's a cohort Tuesday nights at Grove Hall",
      "That moment when you are scanning Twitter and you're all like 'What's with all of these instance variables?' #toomuchRuby @LaunchAcademy_",
      "My first @github 404 error, I am in awe: https://t.co/HK8u626Fxd",
      "A sunny day, a Dorchester panorama and some glimpses of the skyline: #Boston I couldn't be more glad that you're my home",
      "Some thoughts on remaining calm (even in an interview!) after @flomotlik's talk at @LaunchAcademy_ last week: http://t.co/kFgvCD4jmm",
      "@MikeReiss The Gazelle and Gisele. It works."],
    "number of followers"=>27,
    "number of friends"=>84,
    "latest tweet"=>"@lizvdk You are awesome! It will all be good!",
    "number of tweets"=>106,
    "location"=>nil}},
 {"bostonrb"=>
   {"description"=>
     "Follow for BostonRB announcements and other general Ruby and Rails announcements in the Boston area.",
    "last twenty tweets"=>
     ["RT @sarahmei: I had a great time @bostonrb! I'm honored to be a Weirich Fellow. Hope my talk lived up to the legacy. See you again in warme…",
      "@sarahmei's \"Multitudes\" is getting us to think about contributing to Open Source http://t.co/NWFMLLJ8oN",
      "@pat_shaughnessy speaks about ActiveRecord internals http://t.co/1gugEnJRMO",
      "Jam-packed meetup tonight! http://t.co/Svonu8lOnW",
      "We’ll be streaming live tonight: http://t.co/qafgdDBNuU",
      "A huge thanks to @yottaa for sponsoring @sarahmei as this month's Weirich Fellow! Thanks Yottaa!!",
      "Last chance to register for tonight's killer meetup with @sarahmei and @pat_shaughnessy http://t.co/XuTv6jpXzX",
      ".@FessendenTim @yottaa @sarahmei the meeting is actually tomorrow night, Tuesday. Don’t want to confuse anyone. :)",
      "@jaredcosulich they’re out of town “keynote” level speakers that are flown in just to speak at the meeting. we have one tomorrow night.",
      "@jaredcosulich also, we’re always looking for companies to sponsor Wierich Fellows. Sponsors always get a chance to speak to the group.",
      "@jaredcosulich the jobs wiki is very out of date. i would recommend coming and meeting the people who are looking.",
      "@jaredcosulich we don’t let people announce hiring, but we do let people  announce they’re looking for jobs.",
      "Don't miss @sarahmei and @pat_shaughnessy at tomorrow night's meeting. It's going to be epic! http://t.co/n6LiNJ3DhA",
      "RT @pat_shaughnessy: Super excited to have a chance to hear @sarahmei speak Tuesday at @bostonrb ... going to be a fun week!",
      "Come see our latest Weirich Fellow (sponsored by @yottaa), @sarahmei at next week's meeting. http://t.co/ugWjiYN9qS",
      "This is your last chance to sign up for tonight's Project Night! http://t.co/ZC0jni7nOe",
      "Have you registered for tomorrow night's Project Night? Spaces are limited, so hurry up! http://t.co/ANOae4LHLE",
      "Don't miss the incomparable @pat_shaughnessy talk about ActiveRecord at this month's meeting. Register now! http://t.co/T3vhVotdbZ",
      "Don't forget to register for next week's Project Night. http://t.co/gZqEVcsIob",
      "Next month's meeting with @sarahmei and @pat_shaughnessy is open for registrations. Hurry up before it's sold out! http://t.co/4S93Zdn6t9"],
    "number of followers"=>2169,
    "number of friends"=>9,
    "latest tweet"=>
     "RT @sarahmei: I had a great time @bostonrb! I'm honored to be a Weirich Fellow. Hope my talk lived up to the legacy. See you again in warme…",
    "number of tweets"=>1645,
    "location"=>"Boston, MA"}},
 {"judngu"=>
   {"description"=>
     "A former GeoCities kid making my way into modern web development",
    "last twenty tweets"=>
     ["RT @AP: Cartoonists around the world draw in support of those slain at French magazine Charlie Hebdo: http://t.co/nhVLlLcpLc",
      "Great prices on the Jawbone up from best buy today $29 http://t.co/04da9yBf2G",
      "Microsoft to ship new browser with windows 10...Spartan\nhttp://t.co/setXOLgqLi",
      "Santa is real https://t.co/tIeTrUF338 #santatracker #MerryChristmas",
      "Just finished install ruby on rails on my windows pc :)  Now I can be productive on all my computers. weeeeeeeeeee!!",
      "RT @CodeForBoston: Great to see so many @LaunchAcademy_ members at tonight's #weeklyhacknight! #cfabrigade",
      "Central square - Cambridge,MA #ShutItDown http://t.co/Ae9CWnPWzA",
      "Friday at #launchacademy :) http://t.co/uoZxgRa4Rh",
      "RT @codeorg: Did you know the first computer programmer was a woman? Happy 199th birthday Ada Lovelace. http://t.co/zF5UiwKVNS",
      "RT @Microsoft: Get your start in coding with free resources from Microsoft. #HourOfCode https://t.co/GWfKIpatL4",
      "cracking open #therails4way",
      "RT @BostonGlobe: .@harvardmed students stage 15½-minute-long “die-in” to protest Ferguson, NYC cases  http://t.co/3yxpZZfoXA http://t.co/kR…",
      "RT @7News: WATCH LIVE: SKY7 HD over #EricGarner protests in #Cambridge: http://t.co/AOdFe6TDDs #7News http://t.co/jD6qg5YDlV",
      "Picked up a Dell 28\" 4K monitor at the Microsoft Store as a Black Friday present to myself today.  #MicrosoftStore #BlackFriday #dell #4K",
      "Finished my #BlackFriday shopping.  Nothing but relaxing for the rest of the holiday weekend.  Woot!",
      "starting to plan my Black Friday shopping plan #BlackFriday #bestbuy #microsoftstore",
      "RT @gdiBoston: We took up the entire oak table at @cloverHSQ at tonight's Code and Coffee! http://t.co/VHxZSLszxm",
      "developers hate internet explorer, how do you fix this @Microsoft?",
      "Get it free: The 5 Hour Developer Freebie Bundle https://t.co/VaHLQSucE6 via @StackSocial",
      "Listening to Sinatra while learning about Sinatra :)"],
    "number of followers"=>24,
    "number of friends"=>78,
    "latest tweet"=>
     "RT @AP: Cartoonists around the world draw in support of those slain at French magazine Charlie Hebdo: http://t.co/nhVLlLcpLc",
    "number of tweets"=>22,
    "location"=>"Cambridge, MA"}},
 {"lizvdk"=>
   {"description"=>
     "Aspiring Full Stack Developer. Avid Baker & Crafter. Animal Lover.",
    "last twenty tweets"=>
     ["@chrisccerami I may be able to have both but for now I pick visualizations.",
      "@chrisccerami but I think data visualization is more important for my project.",
      "@chrisccerami I think mapbox is better as working with geojson. I switched to gmaps for geolocation/autocomplete.",
      "@MBTA 👍",
      "@MBTA it smelled plasticy in Braintree station. The train smells okay.",
      "Should I be concerned that Braintree station smells like Creepy Crawlers? 🐞🐜🐛🐌 Is the #MBTA using plasticgoop for repairs nowadays?",
      "@dot_the_speck Thanks Zoe! You're awesome!!!!",
      "I'm awesome at breaking my breakable toy!",
      "I switched from mapbox to gmaps. Now I want to switch back to MB. My git history is ugly but I think my code will be cleaner with MB.",
      "RT @JoeIngeno: 'Any fool can write code that a computer can understand. Good programmers write code that humans can understand.' - Martin F…",
      "The cool kids use GEOjson so I did too. Here's how I build it with Ruby: https://t.co/sXFTW9nzWb",
      "\"Thank you so much. This has been very helpful. I found a way to avoid parsing the json and building it to be…\" — Liz http://t.co/RkLrgmu0yq",
      "Fire Master http://t.co/yqXPPv07xg",
      "RT @olivierlacan: I laugh at my own jokes.\n\nIt feels great.",
      "Why did I sit through all 119 minutes of Anchorman 2?",
      "RT @thichnhathanh: Whether this moment is happy or not depends on you. It's you that makes the moment happy. It's not the moment that makes…",
      "RT @NWSBoston: Looked into the record books for Boston to see if not having much snow so far means anything for the season... http://t.co/r…",
      "RT @lukeoneil47: It's pronounced Christmas jift, actually.",
      "RT @melowens: I'm up to my ass in bowls. #backhomeballers @Lesdoggg http://t.co/J1Ifyc3HeW",
      "@freshtilledsoil Looks amazing! Was it delicious?"],
    "number of followers"=>60,
    "number of friends"=>234,
    "latest tweet"=>
     "@chrisccerami I may be able to have both but for now I pick visualizations.",
    "number of tweets"=>228,
    "location"=>"Boston, MA"}},
 {"hchood"=>
   {"description"=>
     "software developer at @Intpd // former instructor at @LaunchAcademy_",
    "last twenty tweets"=>
     ["@bcardarella no problem, thanks for the great walk-through!",
      "RT @dpickett: Aspiring devs, if you need an example of a professional that embodies all we try to teach and more, look to @hchood Thank you…",
      "Status update http://t.co/QyTvq8WpUN",
      "This is how one's last day at Launch go's down http://t.co/aX8oDd2Up7",
      "Desktop smores. Courtesy of Lauren Glicksteen. @LaunchAcademy_ http://t.co/lMtFd3NfXQ",
      "@janetdchuang going to be a developer at Intrepid Pursuits.  Super psyched but also super sad :(",
      "didn't quite make it to Friday without waterworks-ing.  I'm gonna miss this place and all the awesome people here -  @LaunchAcademy_",
      "Omid and progeny http://t.co/IOHRqpxdwY",
      "Winning Christmas so hard right now http://t.co/hPD2o2sui2",
      "#truth http://t.co/2pnwRTcSdC",
      "@kdaigle - \"Ask questions, check your pride.\" Hear, hear. At @LaunchAcademy_",
      "Anyone want tickets to Interpol at HOB tonight? Much as I love them I need a night in.",
      "RT @evancharlz: Friday Fun Time via Launch Votes @LaunchAcademy_ with @hchood http://t.co/ZrY4rAt2az",
      "This governor's race is killing me. Come on Martha!",
      "WHOOOO MAURA!",
      "Seth Moulton is saying all the right things",
      "@gabebw @edwardloveall Expendables 2 was better.  But they are basically all perfection.",
      "@Dan_Kleiman blacked out for 90 minutes. what happened?",
      "@edwardloveall @gabebw haha happy to oblige",
      "Cue triumphant music"],
    "number of followers"=>242,
    "number of friends"=>832,
    "latest tweet"=>
     "@bcardarella no problem, thanks for the great walk-through!",
    "number of tweets"=>207,
    "location"=>"Cambridge, MA"}},
 {"wand_chris"=>
   {"description"=>nil,
    "last twenty tweets"=>
     ["RT @chrisccerami: I recently built my first API in Rails which I hope makes photos from Mars courtesy of @MarsCuriosity more accessible to …",
      "RT @TheDailyWTF: RT @withoutgorms: He's making a database\nHe's filtering twice \nSELECT * FROM customers WHERE behaviour = Nice\nSanta Clause…",
      "@timhwang I'm still in the area and would love to catch up. Unfortunately our couch is not suitable for sleeping on.",
      "@lizvdk I've been using @Mapbox on @HeroicEric 's advice, and I've found their examples and docs to be pretty great",
      "New in web toys I have helped build: an implementation of the card game Set in JS and CSS http://t.co/0D5VA08GzR",
      "I made a thing. It's simple and a little buggy, but it's mine and it's online at http://t.co/Luc8dB8B78",
      "Watching debate at Precinct @VilleForMarkey http://t.co/tp4Xn412Jn"],
    "number of followers"=>30,
    "number of friends"=>73,
    "latest tweet"=>
     "RT @chrisccerami: I recently built my first API in Rails which I hope makes photos from Mars courtesy of @MarsCuriosity more accessible to …",
    "number of tweets"=>7,
    "location"=>nil}},
 {"julissaJM"=>
   {"description"=>
     "Julissa Jansen | Ruby on Rails Developer | @launchacademy_ alum",
    "last twenty tweets"=>
     ["RT @YearlyAwards: We've named @JulissaJM our Least Acrimonious Tweeter of 2014!",
      "@Dan_Kleiman ah! I just saw what was written. I got distracted by the GIANT FACE.",
      "@Dan_Kleiman I have! A little too dedicated for me...",
      "RT @Fara1: \"What about ambulances stuck in protest traffic???\" is the new \"Why couldn't they give Terri Schiavo ice chips???\" Phony parrote…",
      "#OscarsSoWhite it doesn't know what to do with all these credit card offers!",
      "@mxie I have a MBP from 2009 so it's time to upgrade. Which MBA do you have?",
      "Does anyone use a MacBook Air for web development?",
      "@hannanimal their calamari is pretty amazing.",
      "@sarahmei It was great speaking with you yesterday! I'm totally committed to making some open sources contributions.",
      "RT @dbernstein: Boston: you're not mocking @marty_walsh enough for saying no referendum on #Boston2024 while he's suing for referendum on E…",
      "@licaluv whyyyyy?",
      "RT @avashly: \"This award...represents a culture that wants to see themselves as heroes.\" - @HereIsGina #GoldenGlobes #Boricua &lt;3 http://t.c…",
      "RT @SLAwrites: Men accepting awards tonight: \"...and I'd like to thank my dog and my chiropractor and my...\"\nWomen: \"Wow! What an hon...\" *…",
      "RT @MsJamilaAisha: Oprah's gotta amp up the Oprahness to get Ava DuVernay an Oscar. The machine behind Boyhood looks strong.",
      "That Google Play commercial just reminded my of my mortality. I'm going to hug my girlfriend now.",
      "I liked Boyhood...",
      "Well, I thought I'd make it through January without seeing \"Boston Strong\" on television.",
      "Adrian Brody is forever a creep to me after making out with Halle Berry.",
      "@rgay I'm upset Charlie Hunman changed his mind about being Grey.",
      "RT @MarisaLange: If you think you have a stupid question, just remember NASA engineers once asked Sally Ride if 100 tampons were enough for…"],
    "number of followers"=>587,
    "number of friends"=>577,
    "latest tweet"=>
     "RT @YearlyAwards: We've named @JulissaJM our Least Acrimonious Tweeter of 2014!",
    "number of tweets"=>11542,
    "location"=>"Boston, Ma"}},
 {"ashleytbasinger"=>
   {"description"=>
     "Passionate, enthusiastic, seeks the wildly hilarious and extraordinary. An undercover Ashevillian who goes a-wandering.",
    "last twenty tweets"=>
     ["Listening to Dashboard all morning. I think today is going to be awesome. #dashboardconfessional #deskconfessional",
      "It’s going to be one of those days. #saintspreserveus",
      "I love @Uber_BOS! Sign up using my promo code and get $25 off your first ride: http://t.co/EZemJDL9iG Woohoo!",
      "Never have I been so excited to receive a new sketchbook. I want to run shrieking out of the building and start doodling. #designerproblems",
      "I love that I can hear your music through your headphones while I’m listening to mine, especially that violin that’s been on repeat ALL DAY.",
      "RT @TheFryeCompany: It. Is. Freezing.",
      "New coding music: the Skyfall soundtrack. Happy Thursday, all! #Skyfall #codingmusic #thursday",
      "Vintage travel posters! RT @NASAJPL: Printable #Exoplanet Travel Bureau posters online now http://t.co/wuwolGvzJG http://t.co/cZD7qTULFA",
      "Does no one else in the office keep markers in their desk? How else would you color mockup doodles? #designerproblems #crayola",
      "Today’s a day for hot chocolate, Mamma Mia, and new email templates. Perhaps some Flash. #emaildesign #brrrr",
      "It’s a Daughtry kind of day. Where are my Skullcandys at. #daughtry #longliverock #Skullcandy",
      "Since when are the Outlooks so darn picky about height?! #emaildesign",
      "That feeling when you're designing/coding/testing emails, and they just WORK. That, and a large Red Bull. #emaildesign #emailtesting",
      "Wow, super helpful! UX Project Checklist: The UX Design Process From A to Z http://t.co/awq1sqChnh #ux #uxchecklist via @sovesove",
      "Gershwin: Rhapsody in Blue, you are my life saver today. #musicsnob #jazz #emaildesign",
      "Psychosis: the sensation of being so swamped at work that you laugh uncontrollably and accidentally misplace all of your desktop icons.",
      "Eating Kinder Eggs at my desk today- be jealous, Canadian coworkers. Be jealous.",
      "Once again, thanx to @MBTA for leaving out a CT2 on the bus schedule this morning. So happy to be here at Sullivan in the cold. #mbta",
      "Best advice I’ve heard all day! RT @RobertDowneyJr: Be patient, work on your hustle, and exact your revenge. #MondayAdvice",
      "Over a year out of @LaunchAcademy_, and fixing my own Rails problems is still such a joy. #developerlove #geekery"],
    "number of followers"=>83,
    "number of friends"=>188,
    "latest tweet"=>
     "Listening to Dashboard all morning. I think today is going to be awesome. #dashboardconfessional #deskconfessional",
    "number of tweets"=>352,
    "location"=>"Boston"}},
 {"alacritythief"=>
   {"description"=>
     "Web Developer + Illustrator. Web Engineer at @CogoLabs. Graduate of @LaunchAcademy_.",
    "last twenty tweets"=>
     ["Hey @TobitronKahn ! Send me an email to alacritystudios@gmail.com and I'll be happy to answer any questions you may have.",
      "The game I made in JavaScript using Phaser.io on #shipitsaturday at @LaunchAcademy_ is now online, at http://t.co/HnpuJzjP3s. Enjoy!",
      "Learning all the Pythons and the Djangos right now! On a more serious note, I'll blog soon about getting ENV variables in your Django app.",
      "One sign of becoming a software developer: Typing \"g\" in your browser's address bar now autocompletes to GitHub instead of Gmail.",
      "New Blog post: Weeks 9 &amp; 10 @ Launch Academy + Beyond… http://t.co/iyN4PexxtJ",
      "I've been deep in Javascript and Node.js for the past week, with the help of this book: http://t.co/I8uiG8CK4W - Highly recommended.",
      "It seems Vecna is attempting to attract otaku who are into healthcare &amp; robotics (Seen on an MBTA train). http://t.co/E5VnrlltcE",
      "Photo: Seven Sovereigns page 2 - 2014 http://t.co/2DbhipFHi4",
      "Photo: Seven Sovereigns page 1- 2014 More to come… http://t.co/qASi5q7cmg",
      "Ask and ye shall receive: #CaturdayFuntime now has infinite scroll. Productivity worldwide has dropped another 15%. http://t.co/MXK5lHP8On",
      "New Blog Post: Weeks 7 &amp; 8 @ Launch Academy: Caturday Funtime http://t.co/4kXbRKHv8e",
      "My team's app project, \"Caturday Funtime\" is now live! GO SIGN UP and post and rate cats at https://t.co/SEsqHPnXiw ! Thanks @LaunchAcademy_",
      "Apparently #Microsoft thinks odd numbers are bad luck now, so they cut their future losses with 9 and went straight to Windows 10.",
      "My \"Ship-It Saturday\" web app, \"Ask the Duck!\" is online at http://t.co/bR4iXjzQBd! I had a lot of fun working on it! http://t.co/hov5cgrs0E",
      "Made an app on #shipit Saturday! @LaunchAcademy_ http://t.co/d2mhdYELW2",
      "New blog post: Week 6 @ Launch Academy: Sinatra vs Rails http://t.co/SlfEOBoTQy",
      "New blog post: Week 5 @ Launch Academy - http://t.co/EQJQYSZjMR",
      "New blog post: Week 4 Reflections @ Launch Academy -  http://t.co/NnzT6AeYLk",
      "My thanks go to the neat people I met tonight at @bostonrb, and shoutouts go to @thehelenswanson, @dpickett, and @thoughtbot for hosting!",
      "Caught David sleeping for #launcher_sleepy http://t.co/KLk2pqpYaR http://t.co/JjmP2EkViC"],
    "number of followers"=>63,
    "number of friends"=>47,
    "latest tweet"=>
     "Hey @TobitronKahn ! Send me an email to alacritystudios@gmail.com and I'll be happy to answer any questions you may have.",
    "number of tweets"=>222,
    "location"=>"Boston, MA"}}]
end

#YOUR CODE GOES HERE
