---
title: "Meetups in Space - Part 3"
type: "challenge"
description: "Build a web app with Sinatra and Active Record to find places to hang out in space."
tags: "sinatra, active-record, activerecord, databases, migrations, validations"
depends: "meetups-in-space-2"
ignore:
- "meetups-in-space-3.md"
- ".env"
