---
title: "Rails Routes"
type: "article"
description: "Describes how Rails determines which controller should process an incoming request."
tags: "rails, controllers, routes, rest, http, http-request"
