---
title: "Meetups in Space - Part 2"
type: "challenge"
description: "Build a web app with Sinatra and Active Record to find places to hang out in space."
tags: "sinatra, active-record, activerecord, databases, migrations, associations"
depends: "meetups-in-space-1"
ignore:
- "meetups-in-space-2-associations.md"
- ".env"
