---
title: "Grocery List"
type: "challenge"
description: "Display and append to a list of groceries via a web application."
depends: "news-aggregator"
visibility: "assign"
progress_attribute: "systems_check_1"
ignore:
- "grocery-list.md"
