---
title: "Random Brussels Sprouts with Ajax"
type: "challenge"
description: "Using Ajax to Generate Random Brussels Sprouts Recipes"
depends: "rock-paper-scissors"
ignore:
- "evening-ajax-brussels-sprouts.md"
